version: "2"
linters:
  enable:
    - gosec
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    staticcheck:
      checks:
        - all
        - -ST1003
        - -ST1005
        - -ST1006
        - -ST1023
        - -QF1001
        - -QF1003
        - -QF1004
        - -QF1008
        - -QF1011
run:
  timeout: 2m
