name: Build & Test

on: 
  push:
    branches: ['**']

  # Allow workflow to be triggered from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    name: Build & Test on Go v${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16.x']

    env:
      GO111MODULE: on

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go v${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: v5/go.sum
      - name: Install dependencies
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.49.0
          golangci-lint version
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          gosec version
      - name: Build & Test
        run: make ci      
