name: golangci-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: v4
          args: --build-tags=all
